import React, { useState } from 'react';
import { Download, Copy, CheckCircle, FileText, Share2, Printer } from 'lucide-react';

const ExportFunctionality = ({ analysisData, onExportPDF, onPrint }) => {
  const [copiedFormat, setCopiedFormat] = useState(null);
  const [exportProgress, setExportProgress] = useState(null);

  const copyToClipboard = async (text, format) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedFormat(format);
      setTimeout(() => setCopiedFormat(null), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  const downloadJSON = () => {
    setExportProgress('json');
    
    try {
      const jsonString = JSON.stringify(analysisData, null, 2);
      const blob = new Blob([jsonString], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `pharmaguard-analysis-${analysisData.patient_id}-${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);
      
      setTimeout(() => setExportProgress(null), 1000);
    } catch (error) {
      console.error('Error downloading JSON:', error);
      setExportProgress(null);
    }
  };

  const downloadCSV = () => {
    setExportProgress('csv');
    
    try {
      // Create CSV content
      const csvContent = generateCSV();
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `pharmaguard-analysis-${analysisData.patient_id}-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);
      
      setTimeout(() => setExportProgress(null), 1000);
    } catch (error) {
      console.error('Error downloading CSV:', error);
      setExportProgress(null);
    }
  };

  const generateCSV = () => {
    const headers = [
      'Patient ID',
      'Drug Name',
      'Risk Level',
      'Confidence Score',
      'Severity Level',
      'Recommendation',
      'Dosage',
      'Genes Analyzed',
      'Variants Found',
      'Analysis Date'
    ];

    const row = [
      analysisData.patient_id,
      analysisData.drug_info?.name || '',
      analysisData.risk_assessment?.risk_level || '',
      analysisData.risk_assessment?.confidence || '',
      analysisData.risk_assessment?.severity || '',
      analysisData.risk_assessment?.recommendation || '',
      analysisData.risk_assessment?.dosage || '',
      Object.keys(analysisData.pharmacogenomic_profile || {}).length,
      analysisData.quality_metrics?.variant_coverage || 0,
      analysisData.quality_metrics?.analysis_timestamp || ''
    ];

    return [headers.join(','), row.join(',')].join('\n');
  };

  const generateSummaryText = () => {
    const risk = analysisData.risk_assessment;
    const quality = analysisData.quality_metrics;
    
    return `PharmaGuard Analysis Summary
=====================================

Patient ID: ${analysisData.patient_id}
Drug: ${analysisData.drug_info?.name}
Analysis Date: ${quality?.analysis_timestamp}

RISK ASSESSMENT
----------------
Risk Level: ${risk?.risk_level}
Confidence: ${(risk?.confidence * 100).toFixed(1)}%
Severity: ${risk?.severity}
Evidence Level: ${risk?.evidence_level || 'N/A'}

RECOMMENDATION
--------------
${risk?.recommendation || 'No recommendation available'}

DOSAGE
--------
${risk?.dosage || 'Standard dosing'}

WARNINGS
--------
${risk?.warnings?.join('\n') || 'No warnings'}

GENETIC FINDINGS
----------------
${Object.entries(analysisData.pharmacogenomic_profile || {})
  .map(([gene, profile]) => 
    `${gene}: ${profile.phenotype} (${profile.variant_count} variants)`
  ).join('\n')}

QUALITY METRICS
----------------
VCF Quality Score: ${quality?.vcf_quality_score?.toFixed(2) || 'N/A'}
Total Variants: ${quality?.total_variants_found || 0}
Target Variants: ${quality?.variant_coverage || 0}
Processing Time: ${quality?.processing_time_ms || 0}ms

---
Generated by PharmaGuard Pharmacogenomic Risk Prediction System
For educational and research purposes only. Not for clinical use.`;
  };

  const shareData = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `PharmaGuard Analysis - ${analysisData.patient_id}`,
          text: `Pharmacogenomic analysis for ${analysisData.drug_info?.name}: ${analysisData.risk_assessment?.risk_level} risk level`,
          url: window.location.href
        });
      } catch (error) {
        console.log('Share cancelled or failed:', error);
      }
    } else {
      // Fallback: copy summary to clipboard
      copyToClipboard(generateSummaryText(), 'summary');
    }
  };

  const printReport = () => {
    setExportProgress('print');
    onPrint?.();
    setTimeout(() => setExportProgress(null), 1000);
  };

  const ExportButton = ({ 
    icon: Icon, 
    label, 
    onClick, 
    format, 
    disabled = false,
    progress = null 
  }) => (
    <button
      onClick={onClick}
      disabled={disabled || progress !== null}
      className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-all ${
        disabled || progress !== null
          ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
          : 'bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 hover:border-gray-400'
      }`}
    >
      {progress === format ? (
        <CheckCircle className="w-4 h-4 text-green-500" />
      ) : (
        <Icon className="w-4 h-4" />
      )}
      <span>{progress === format ? 'Done!' : label}</span>
    </button>
  );

  if (!analysisData) {
    return (
      <div className="text-center py-8">
        <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
        <p className="text-gray-500">No data available to export</p>
      </div>
    );
  }

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6">
      <div className="flex items-center space-x-3 mb-6">
        <Download className="w-6 h-6 text-gray-600" />
        <h2 className="text-xl font-semibold text-gray-900">Export Analysis Results</h2>
      </div>

      {/* Export Options */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        <ExportButton
          icon={Download}
          label="Download JSON"
          onClick={downloadJSON}
          format="json"
          progress={exportProgress}
        />
        
        <ExportButton
          icon={Download}
          label="Download CSV"
          onClick={downloadCSV}
          format="csv"
          progress={exportProgress}
        />
        
        <ExportButton
          icon={Copy}
          label="Copy JSON"
          onClick={() => copyToClipboard(JSON.stringify(analysisData, null, 2), 'json')}
          format="json"
        />
        
        <ExportButton
          icon={Copy}
          label="Copy Summary"
          onClick={() => copyToClipboard(generateSummaryText(), 'summary')}
          format="summary"
        />
        
        <ExportButton
          icon={Printer}
          label="Print Report"
          onClick={printReport}
          format="print"
          progress={exportProgress}
        />
        
        <ExportButton
          icon={Share2}
          label="Share Results"
          onClick={shareData}
          format="share"
        />
      </div>

      {/* File Information */}
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
        <h3 className="text-sm font-medium text-gray-900 mb-3">Export Information</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <span className="font-medium text-gray-700">JSON Format:</span>
            <p className="text-gray-600">Complete analysis data with all details</p>
          </div>
          <div>
            <span className="font-medium text-gray-700">CSV Format:</span>
            <p className="text-gray-600">Summary data for spreadsheet analysis</p>
          </div>
          <div>
            <span className="font-medium text-gray-700">Summary Text:</span>
            <p className="text-gray-600">Human-readable summary report</p>
          </div>
          <div>
            <span className="font-medium text-gray-700">Print Report:</span>
            <p className="text-gray-600">Formatted clinical report</p>
          </div>
        </div>
      </div>

      {/* Data Preview */}
      <div className="mt-6">
        <h3 className="text-sm font-medium text-gray-900 mb-3">Quick Preview</h3>
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <span className="font-medium text-gray-700">Patient:</span>
              <p className="text-gray-600">{analysisData.patient_id}</p>
            </div>
            <div>
              <span className="font-medium text-gray-700">Drug:</span>
              <p className="text-gray-600">{analysisData.drug_info?.name}</p>
            </div>
            <div>
              <span className="font-medium text-gray-700">Risk Level:</span>
              <p className="text-gray-600">{analysisData.risk_assessment?.risk_level}</p>
            </div>
            <div>
              <span className="font-medium text-gray-700">Confidence:</span>
              <p className="text-gray-600">
                {((analysisData.risk_assessment?.confidence || 0) * 100).toFixed(1)}%
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Usage Guidelines */}
      <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex items-start space-x-2">
          <FileText className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-blue-800">
            <p className="font-medium mb-2">Usage Guidelines:</p>
            <ul className="space-y-1 text-xs">
              <li>• <strong>JSON:</strong> Complete data for developers and researchers</li>
              <li>• <strong>CSV:</strong> Summary data for Excel/Google Sheets analysis</li>
              <li>• <strong>Summary:</strong> Human-readable report for documentation</li>
              <li>• <strong>Print:</strong> Formatted clinical report for healthcare providers</li>
              <li>• All exports are for educational/research purposes only</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Success Messages */}
      {copiedFormat && (
        <div className="mt-4 flex items-center space-x-2 p-3 bg-green-50 border border-green-200 rounded-lg">
          <CheckCircle className="w-5 h-5 text-green-600" />
          <span className="text-green-800 text-sm">
            {copiedFormat === 'json' ? 'JSON data' : 'Summary text'} copied to clipboard!
          </span>
        </div>
      )}
    </div>
  );
};

export default ExportFunctionality;
